= Declarations

++++
<link rel="stylesheet" href="../style.css" type="text/css">
++++

:tab: &nbsp;&nbsp;&nbsp;&nbsp;
:hardbreaks-option:

:star: *
:under: _

`_type-keyword_`: one of
{tab} `*int8*` `*int16*` `*int32*` `*int64*` `*int*`
{tab} `*nat8*` `*nat16*` `*nat32*` `*nat64*` `*nat*`
{tab} `*bool*` `*char*` `*str*`
{tab} `*real32*` `*real64*` `*real*`
{tab} `*imag32*` `*imag64*` `*imag*`
{tab} `*cplex32*` `*cplex64*` `*cplex*`

`_type-qualifier_`: one of
{tab} `*var*` `*invar*`

`_borrow-qualifier_`: one of
{tab} `*&*` `*$*`

`_identifier-declaration_`:
{tab} `_type-keyword_` `_array-dimension-list_`~opt~ `_identifier-list_`
`_array-dimension-list_`:
{tab} `*[*` `*]*`
{tab} `_array-dimension-list_` `*[*` `*]*`
`_identifier-list_`:
{tab} `_identifier_`
{tab} `_identifier-list_` `*,*` `_identifier_`

`_variable-declaration_`:
{tab} `*var*`~opt~ `_identifier-declaration_`

`_invariable-declaration_`:
{tab} `*invar*` `_identifier-declaration_`

`_full-type_`:
{tab} `_type-qualifier_`~opt~ `_type-keyword_` `_array-dimension-list_`~opt~

`_function-declaration_`:
{tab} `*fun*` `_identifier_` `*(*` `_parameter-list_`~opt~ `_defaults_`~opt~ `*)*` `_return-type_`~opt~
`_parameter-list_`:
{tab} `_parameter_`
{tab} `_parameter-list_` `*,*` `_parameter_`
`_defaults_`:
{tab} `*,*` `_default-parameter-list_`
`_default-parameter-list_`:
{tab} `_default-parameter_`
{tab} `_default-parameter-list_` `*,*` `_default-parameter_`
`_parameter_`:
{tab} `_full-type_` `_borrow-qualifier_`~opt~ `_identifier_`~opt~
`_default-parameter_`:
{tab} `_full-type_` `_identifier_` `*=*` `_expression_`
`_return-type_`:
{tab} `*\->*` `_full-type_` `*$*`~opt~
