= Declarations

++++
<link rel="stylesheet" href="../style.css" type="text/css">
++++

:tab: &nbsp;&nbsp;&nbsp;&nbsp;
:hardbreaks-option:

:star: *
:under: _

`_type-name_`:
{tab} `_reference-type-name_`
{tab} `_reference-type-name_` `_alignment-specifier_`

`_reference-type-name_`:
{tab} `_non-reference-type-name_`
{tab} `_non-reference-type-name_` `_type-qualifier_`~opt~ `*@*`

`_non-reference-type-name_`:
{tab} `_specifiers-and-qualifiers_` `_type-specifier_`
{tab} `_non-reference-type-name_` `_type-qualifier_`~opt~ `*[*` `*{star}*` `*]*`
{tab} `_non-reference-type-name_` `_type-qualifier_`~opt~ `*[*` `*>=*`~opt~ `_assignment-expression_` `*]*`
{tab} `_non-reference-type-name_` `_type-qualifier_`~opt~ `*^*`

`_specifiers-and-qualifiers_`:
{tab} `_storage-class-specifier_`~opt~ `_type-qualifier_`~opt~

`_alignment-specifier_`:
{tab} `*aligned*` `*to*` `_constant-expression_`
{tab} `*aligned*` `*to*` `_type-name_`

`_storage-class-specifier_`:
{tab} `*external*`
{tab} `*register*`
{tab} `*static*`
{tab} `*static*`~opt~ `*thread*`~opt~ `*local*`
{tab} `*external*`~opt~ `*thread*`~opt~ `*local*`

`_type-qualifier_`:
{tab} `*atomic*` `_type-qualifier_`~opt~
{tab} `*const*` `_type-qualifier_`~opt~
{tab} `*restrict*` `_type-qualifier_`~opt~
{tab} `*volatile*` `_type-qualifier_`~opt~

`_type-specifier_`:
{tab} `*auto*`
{tab} `*void*`
{tab} `*str*`
{tab} `_alias_`
{tab} `_numeric-type-specifier_`
{tab} `*func*` `*(*` `*(*` `_function-variadic-list_`~opt~ `*)*` `*)*`
{tab} `*func*` `*(*` `*(*` `_function-variadic-list_`~opt~ `*)*` `*\->*`  `_type-name_` `*)*`

`_numeric-type-specifier_`:
{tab} `_numeric-set-specifier_`~opt~ `*+*`~opt~ `_integer-type-specifier_`
{tab} `_numeric-set-specifier_`~opt~ `_floating-type-specifier_`

`_numeric-set-specifier_`:
{tab} `*complex*`
{tab} `*imaginary*`
{tab} `*real*`

`_integer-type-specifier_`:
{tab} `*bool*`
{tab} `*char*`
{tab} `*short*` `*int*`~opt~
{tab} `*int*`
{tab} `*long*` `*int*`~opt~

`_floating-type-specifier_`:
{tab} `*float*`
{tab} `*double*` `*float*`~opt~

`_declaration_`:
{tab} `_variable-declaration_`
{tab} `_declaration_` `*,*` `_variable-declaration_`

`_variable-declaration_`:
{tab} `_element-declaration_`  `_variable-initalizer_`~opt~

`_element-declaration_`:
{tab} `_type-name_` `_identifier_`
{tab} `_element-declaration_` `*,*` `_type-name_`~opt~ `_identifier_`

`_variable-initalizer_`:
{tab} `*=*` `_initializer_`

`_initializer_`:
{tab} `_assignment-expression_`
{tab} `_initializer-alloc_`
{tab} `_initializer-compound-literal_`

`_initializer-alloc_`:
{tab} `*alloc*` `_initializer-alloc-arguments_`~opt~
{tab} `*realloc*` `_expression_` `_initializer-realloc-arguments_`~opt~

`_initializer-alloc-arguments_`:
{tab} `*as*` `_initializer_`

`_initialzier-realloc-arguments_`:
{tab} `*as*` `_initializer_`
{tab} `*to*` `_initializer_`
{tab} `*to*` `_initializer_` `*as*` `_initializer_`

`_initializer-compound-literal_`:
{tab} `*[*` `_generator_` `*]*`
{tab} `*{*` `_generator_` `*}*`
{tab} `*[*` `_initializer-list_` `*,*`~opt~ `*]*`
{tab} `*{*` `_initializer-list_` `*,*`~opt~ `*}*`

`_generator_`:
{tab} `*yield*` `_initializer_` `_generator-loop_` `_generator-conditional_`~opt~
{tab} `_generator-constant_` `*to*` `_generator-constant_`

`_generator-loop_`:
{tab} `*for*` `_element-declaration_` `*in*` `_safe-initializer_` `_generator-loop_`~opt~

`_safe-initializer_`:
{tab} `_logical-or-expression_`
{tab} `_initializer-alloc_`
{tab} `_initializer-compound-literal_`

`_generator-conditional_`:
{tab} `*if*` `_expression_`

`_generator-constant_`:
{tab} `_integer-constant_`
{tab} `_character-constant_`

`_initializer-list_`:
{tab} `_designation_`~opt~ `_initializer_`
{tab} `_initailizer-list_` `*,*` `_designation_`~opt~ `_initializer_`

`_designation_`:
{tab} `*[*` `_constant-expression_` `*]*` `*:*`
{tab} `*[*` `_generator-constant_` `*to*` `_generator-constant_` `*]*` `*:*`
{tab} `_constant-expression_` `*:*`

`_function-declaration_`:
{tab} `_function-specifier_`~opt~ `_identifier_` `_function-values_` `*:*` `_block-statement_`

`_function-specifier_`:
{tab} `_specifiers-and-qualifiers_` `*inline*` `*deviant*`~opt~ `*func*`~opt~
{tab} `_specifiers-and-qualifiers_` `*deviant*` `*inline*`~opt~ `*func*`~opt~

`_function-values_`:
{tab} `*(*` `_function-variadic-list_`~opt~ `*)*` `_function-return-type_`~opt~

`_function-variadic-list_`:
{tab} `_function-parameter-list_`
{tab} `_function-parameter-list_` `*,*` `_type-name_` `*{star}*` `_identifier_`~opt~

`_function-parameter-list_`:
{tab} `_function-parameter_`
{tab} `_function-parameter-list_` `*,*` `_function-parameter_`

`_function-parameter_`:
{tab} `_type-name_` `_identifier_`~opt~

`_function-return-type_`:
{tab} `*\->*` `_type-name_`

`_structure-declaration_`:
{tab} `_specifiers-and-qualifiers_` `_structure-type_` `_identifier_` `*:*` `_block-statement_`

`_structure-type_`:
{tab} `*enum*`
{tab} `*struct*`
{tab} `*union*`

`_declaration-header-list_`:
{tab} `_declaration-header_`
{tab} `_declaration-header-list_` `_declaration-header_`

`_declaration-header_`:
{tab} `_template-declaration_`
{tab} `_decorator-declaration_`

`_template-declaration_`:
{tab} `*template*` `*with*` `_template-parameter-list_` `*,*`~opt~ `_line-end_`

`_template-parameter-list_`:
{tab} `_template-parameter_`
{tab} `_template-parameter-list_` `*,*` `_template-parameter_`

`_template-parameter_`:
{tab} `*type*` `_identifier_`

`_decorator-declaration_`:
{tab} `*decorate*` `*with*` `_decorator-parameter-list_` `*,*`~opt~ `_line-end_`

`_decorator-parameter-list_`:
{tab} `_decorator-parameter_`
{tab} `_decorator-parameter-list_` `*,*` `_decorator-parameter_`

`_decorator-parameter_`:
{tab} `_identifier_`
{tab} `_identifier_` `*(*` `_argument-epression-list_`~opt~ `*)*`
