= Declarations

++++
<link rel="stylesheet" href="../style.css" type="text/css">
++++

:tab: &nbsp;&nbsp;&nbsp;&nbsp;
:hardbreaks-option:

:star: *
:under: _

`_type-keyword_`: one of
{tab} `*int8*` `*int16*` `*int32*` `*int64*` `*int*`
{tab} `*nat8*` `*nat16*` `*nat32*` `*nat64*` `*nat*`
{tab} `*bool*` `*char*`
{tab} `*real32*` `*real64*` `*real*`
{tab} `*imag32*` `*imag64*` `*imag*`
{tab} `*cplex32*` `*cplex64*` `*cplex*`

`_type-qualifier_`: one of
{tab} `*var*` `*invar*`

`_borrow-qualifier_`: one of
{tab} `*&*` `*$*`

`_identifier-declaration_`:
{tab} `_type-keyword_` `_identifier-list_`
`_identifier-list_`:
{tab} `_identifier_`
{tab} `_identifier-list_` `*,*` `_identifier_`

`_variable-declaration_`:
{tab} `*var*`~opt~ `_identifier-declaration_`

`_invariable-declaration_`:
{tab} `*invar*` `_identifier-declaration_`

`_function-declaration_`:
{tab} `*fun*` `_identifier_` `*(*` `function-parameter-list`~opt~ `*)*` `_function-return-type_`~opt~
`_function-parameter-list_`:
{tab} `_function-parameter_`
{tab} `_function-parameter-list_` `*,*` `_function-parameter_`
`_function-parameter_`:
{tab} `_type-qualifier_`~opt~ `_type-keyword_` `_borrow-qualifier_`~opt~ `_identifier_`~opt~
`_function-return-type_`:
{tab} `*\->*` `_type-qualifier_`~opt~ `_type-keyword_` `*$*`~opt~
