= Expressions

++++
<link rel="stylesheet" href="../style.css" type="text/css">
++++

:tab: &nbsp;&nbsp;&nbsp;&nbsp;
:hardbreaks-option:

:star: *

`_primary-expression_`:
{tab} `_identifier_`
{tab} `_constant_`
{tab} `_string-literal_`
{tab} `*(*` `_expression_` `*)*`
{tab} `*|*` `_expression_` `*|*`

`_postfix-expression_`:
{tab} `_primary-expression_`
{tab} `_postfix-expression_` `*[*` `_assignment-expression_`~opt~ `_slice-operator_`~opt~ `*]*`
{tab} `_postfix-expression_` `*(*` `_argument-expression-list_`~opt~ `*)*`
{tab} `_postfix-expression_` `*.*` `_identifier_`
{tab} `_postfix-expression_` `*\->*` `_identifier_`
{tab} `_postfix-expression_` `_postfix-unary-operator_`
{tab} `_postfix-compound-literal_`

`_slice-operator_`:
{tab} `*:*` `_assignment-expression_`~opt~
{tab} `*:*` `_assignment-expression_`~opt~ `*:*` `_assignment-expression_`~opt~

`_postfix-unary_operator_`: one of
{tab} `*++*` `*--*` `*%*` `*!*`

`_postfix-compound-literal_`:
{tab} `*(*` `_type-name_` `*)*` `*(*` `_array-initializer-list_` `*,*`~opt~ `*)*`
{tab} `*(*` `_type-name_` `*)*` `*[*` `_array-initializer-list_` `*,*`~opt~ `*]*`
{tab} `*(*` `_type-name_` `*)*` `*{*` `_initializer-list_` `*,*`~opt~ `*}*`
{tab} `*(*` `_type-name_` `*)*` `_initializer-comprehension_`

`_argument-expression-list_`:
{tab} `_assignment-expression_`
{tab} `_argument-expression-list_` `*,*` `_assignment-expression_`

`_prefix-deviation-expression_`:
{tab} `_postfix-expression_`
{tab} `*++*` `_prefix-deviation-expression_`
{tab} `*--*` `_prefix-deviation-expression_`

`_exponential-expression_`:
{tab} `_prefix-deviation-expression_`
{tab} `_exponential-expression_` `*{star}{star}*` `_cast-expression_`

`_unary-expression_`:
{tab} `_exponential-expression_`
{tab} `_unary-operator_` `_cast-expression_`
{tab} `_unary-type-expression_`

`_unary-operator_`: one of
{tab} `*^*` `*@*` `*-*` `*!*` `*~*` `*~<*` `*~>*`

`_unary-type-expression_`:
{tab} `_unary-type-keyword_` `*of*` `_expression_`
{tab} `_unary-type-keyword_` `*of*` `*(*`~opt~ `_type-name_` `*)*`~opt~

`_unary-type-keyword_`: one of
{tab} `*align*` `*size*` `*type*`

`_cast-expression_`:
{tab} `_unary-expression_`
{tab} `*(*` `_type-name_` `*)*` `_cast-expression_`

`_multiplicative-expression_`:
{tab} `_cast-expression_`
{tab} `_multiplicative-expression_` `*{star}*` `_cast-expression_`
{tab} `_multiplicative-expression_` `*/*` `_cast-expression_`
{tab} `_multiplicative-expression_` `*mod*` `_cast-expression_`

`_additive-expression_`:
{tab} `_multiplicative-expression_`
{tab} `_additive-expression_` `*+*` `_multiplicative-expression_`
{tab} `_additive-expression_` `*-*` `_multiplicative-expression_`

`_shift-expression_`:
{tab} `_additive-expression_`
{tab} `_shift-expression_` `*<<*` `_additive-expression_`
{tab} `_shift-expression_` `*>>*` `_additive-expression_`

`_bitwise-and-expression_`:
{tab} `_shift-expression_`
{tab} `_bitwise-and-expression_` `*&*` `_shift-expression_`

`_bitwise-xor-expression_`:
{tab} `_bitwise-and-expression_`
{tab} `_bitwise-xor-expression_` `*$*` `_bitwise-and-expression_`

`_bitwise-or-expression_`:
{tab} `_bitwise-xor-expression_`
{tab} `_bitwise-or-expression_` `*|*` `_bitwise-xor-expression_`

`_comparative-expression_`:
{tab} `_bitwise-or-expression_`
{tab} `_comparative-expression_` `_comparative-operator_` `_bitwise-or-expression_`

`_comparative-operator_`: one of
{tab} `*<*` `*>*` `*\<=*` `*>=*` `*==*` `*!=*` `*is*` `*is not*` `*in*` `*not in*`

`_logical-not-expression_`:
{tab} `_comparative-expression_`
{tab} `*not*` `_logical-not-expression_`

`_logical-and-expression_`:
{tab} `_logical-not-expression_`
{tab} `_logical-and-expression_` `*and*` `_logical-not-expression_`

`_logical-or-expression_`:
{tab} `_logical-and-expression_`
{tab} `_logical-or-expression_` `*or*` `_logical-and-expression_`

`_conditional-expression_`:
{tab} `_logical-or-expression_`
{tab} `_logical-or-expression_` `*if*` `_expression_` `*else*` `_conditional-expression_`

`_assignment-expression_`:
{tab} `_conditional-expression_`
{tab} `_conditional-expression_` `_assignment-operator_` `_assignment-expression_`

`_assignment-operator_`: one of
{tab} `*=*` `*{star}{star}=*` `*{star}=*` `*/=*` `*%=*` `*+=*` `*-=*`
{tab} `*<\<=*` `*>>=*` `*&=*` `*|=*` `*$=*`

`_expression_`:
{tab} `_assignment-expression_`
{tab} `_expression_` `*,*` `_assignment-expression_`

`_constant-expression_`:
{tab} `_conditional-expression_`
