= Statements

++++
<link rel="stylesheet" href="../style.css" type="text/css">
++++

:tab: &nbsp;&nbsp;&nbsp;&nbsp;
:hardbreaks-option:

:star: *

`_expression-statement_`:
{tab} `_expression_` `_line-end_`

`_assignment-statement_`:
{tab} `_expression-list_` `_line-end_`
{tab} `_identifier-list_` `*=*` `_assignment-statement_`
`_expression-list_`:
{tab} `_expression_`
{tab} `_expression-list_` `*,*` `_expression_`

`_variable-definition_`:
{tab} `_variable-declaration_` `*=*` `_assignment-statement_`

`_invariable-definition_`:
{tab} `_invariable-declaration_` `*=*` `_assignment-statement_`

`_identifier-statement_`:
{tab} `_variable-declaration_` `_line-end_`
{tab} `_variable-definition_`
{tab} `_invariable-definition_`

`_augmented-assignment-statement_`:
{tab} `_assignment-statement_`
{tab} `_identifier_` `_augmented-assignment-operator_` `_expression-statement_`
`_augmented-assignment-operator_`: one of
{tab} `*^=*`, `*{star}=*`, `*/=*`, `*%=*`, `*+=*`, `*-=*`
{tab} `*<\<=*`, `*>>=*`, `*&=*`, `*$=*`, `*|=*`

`_statement_`:
{tab} `_identifier-statement_`
{tab} `_augmented-assignment-statement_`

`_file-statement_`:
{tab} `_statement_`
{tab} `_file-statement_` `_statement_`
