= Statements

++++
<link rel="stylesheet" href="../style.css" type="text/css">
++++

:tab: &nbsp;&nbsp;&nbsp;&nbsp;
:hardbreaks-option:

:star: *

`_expression-statement_`:
{tab} `_expression_`

`_assignment-statement_`:
{tab} `_expression-list_`
{tab} `_identifier-list_` `*=*` `_assignment-statement_`
`_expression-list_`:
{tab} `_expression_`
{tab} `_expression-list_` `*,*` `_expression_`

`_variable-definition_`:
{tab} `_variable-declaration_` `*=*` `_assignment-statement_`

`_invariable-definition_`:
{tab} `_invariable-declaration_` `*=*` `_assignment-statement_`

`_identifier-statement_`:
{tab} `_variable-declaration_`
{tab} `_variable-definition_`
{tab} `_invariable-definition_`

`_augmented-assignment-statement_`:
{tab} `_assignment-statement_`
{tab} `_identifier_` `_augmented-assignment-operator_` `_expression-statement_`
`_augmented-assignment-operator_`: one of
{tab} `*^=*`, `*{star}=*`, `*/=*`, `*%=*`, `*+=*`, `*-=*`
{tab} `*<\<=*`, `*>>=*`, `*&=*`, `*$=*`, `*|=*`

`_line-statement-component_`:
{tab} `_expression-statement_`
{tab} `_augmented-assignment-statement_`
{tab} `_identifier-statement_`

`_line-statement_`:
{tab} `_line-statement-component_` `_line-end_`

`_blockable-statement-component_`:
{tab} `_line-statement-component_`
{tab} `*pass*`
{tab} `*break*` `_label_`~opt~
{tab} `*continue*` `_label_`~opt~
{tab} `*return*` `_expression_`~opt~

`_blockable-statement_`:
{tab} `_blockable-statement-component_` `_line-end_`

`_block-statement_`:
{tab} `_blockable-statement_`
{tab} `_newline-block-statement_`
`_newline-block-statement_`:
{tab} `*\n*` `_block-indent_` `_statement_` `_newline-block-statement_`~opt~
{tab} `*\n*` `_block-indent_` `_blockable-statement_` `_newline-block-statement_`~opt~
`_block-indent_`:
{tab} one `indent` per line of the next statement per number of nested blocks

`_if-statement_`:
{tab} `*if*` `_expression_` `*:*` `_block-statement_` `_else-if-statement_`~opt~ `_else-statement_`~opt~
`_else-if-statement_`:
{tab} `*else*` `*if*` `_expression_` `*:*` `_block-statement_`
{tab} `_else-if-statement_` `*else*` `*if*` `_expression_` `*:*` `_block-statement_`
`_else-statement_`:
{tab} `*else*` `*:*` `_block-statement_`

`_while-statement_`:
{tab} `_label_`~opt~ `*while*` `_expression_` `*:*` `_block-statement_`
`_label_`:
{tab} `_identifier_`

`_do-while-statement_`:
{tab}  `_label_`~opt~ `*do*` `*:*` `_do-while-block-statement_` `*while*` `_expression_` `_line-end_`
{tab} `*do*` `_label_`~opt~ `*:*` `_do-while-block-statement_` `*while*` `_expression_` `_line-end_`
`_do-while-block-statement_`:
{tab} `_blockable-statement-component_`
{tab} `_block-statement_`

`_function-definition_`:
{tab} `_function-declaration_` `*:*` `_block-statement_`

`_function-statement_`:
{tab} `_function-declaration_` `_line-end_`
{tab} `_function-definition_`

`_statement_`:
{tab} `_line-statement_`
{tab} `_if-statement_`
{tab} `_while-statement_`
{tab} `_do-while-statement_`
{tab} `_function-statement_`

`_file-statement_`:
{tab} `_statement_`
{tab} `_file-statement_` `_statement_`
