= Tokens

++++
<link rel="stylesheet" href="../style.css" type="text/css">
++++

:tab: &nbsp;&nbsp;&nbsp;&nbsp;
:hardbreaks-option:

:star: *
:under: _
:tick: `
:stick: \`

`_token_`:
{tab} `_keyword_`
{tab} `_identifier_`
{tab} `_constant_`
{tab} `_string-literal_`
{tab} `_operator_`
{tab} `_keyword-operator_`
{tab} `_punctuator_`

== Keywords
`_keyword_`: one of
{tab} `*include*` `*define*` `*redefine*` `*undefine*` `*defined*`
{tab} `*assert*`
{tab} `*alias*` `*as*`
{tab} `*align*` `*size*` `*type*` `*of*` `*aligned*` `*to*`
{tab} `*alloc*` `*realloc*` `*dealloc*` `*bytes*`
{tab} `*external*` `*register*` `*static*` `*thread*` `*local*`
{tab} `*atomic*` `*const*` `*restrict*` `*volatile*`
{tab} `*template*` `*decorate*` `*inline*` `*deviant*`
{tab} `*complex*` `*imaginary*` `*real*`
{tab} `*auto*` `*void*` `*str*` `*float*` `*double*`
{tab} `*bool*` `*char*` `*short*` `*int*` `*long*`
{tab} `*enum*` `*struct*` `*union*`
{tab} `*if*` `*else*` `*match*` `*with*`
{tab} `*for*` `*do*` `*while*`
{tab} `*manage*` `*c*` `*asm*` `*block*`
{tab} `*break*` `*continue*` `*pass*` `*return*` `*yield*`
{tab} `*True*` `*False*` `*Null*` `*Infinity*` `*NaN*` `*Pi*`

== Identifiers
`_identifier_`:
{tab} `_identifier-nondigit_`
{tab} `_identifier_` `_identifier-nondigit_`
{tab} `_identifier_` `_digit_`
{tab} `_operator-function-identifier_`

`_operator-function-identifier_`:
{tab} `*{under}{under}operator*` `_operator-string_` `*{under}{under}*`
{tab} `*{under}{under}*` `_operator-string_` `*operator{under}{under}*`

`_operator-string_`:
{tab} a string of symbols, without spaces, composing a single `_operator_`

`_identifier-nondigit_`:
{tab} `_nondigit_`
{tab} `_universal-character-name_`
{tab} other implementation-defined characters

`_nondigit_`: one of
{tab} `*{under}*`
{tab} `_letter_`

`_letter_`: one of
{tab} english letters `*a*` to `*z*`
{tab} english letters `*A*` to `*Z*`

`_digit_`: one of
{tab} integers `*0*` to `*9*`

`_universal-character-name_`:
{tab} `*\u*` `_hex-quad_`
{tab} `*\U*` `_hex-quad_` `_hex-quad_`

`_hex-quad_`:
{tab} `_hexadecimal-digit_` `_hexadecimal-digit_` `_hexadecimal-digit_` `_hexadecimal-digit_`

== Constants
`_constant_`:
{tab} `_integer-constant_` `*bytes*`~opt~
{tab} `_floating-constant_`
{tab} `_enumeration-constant_`
{tab} `_character-constant_`

`_integer-constant_`:
{tab} `_sign_`~opt~  `_decimal-constant_`
{tab} `_sign_`~opt~ `_base-n-constant_`

`_decimal-constant_`:
{tab} `_digit-sequence_`

`_digit-sequence_`:
{tab} `_digit_`
{tab} `_digit-sequence_` `_digit_`

`_base-n-constant_`:
{tab} `_base-n-digit-sequence_`

`_base-n-digit-sequence_`:
{tab} `_base-n-prefix_` `_base-n-digit_`
{tab} `_base-n-digit-sequence_` `_base-n-digit_`

`_base-n-digit_`: one of
{tab} `_digit_`
{tab} english letters `*A*` to `*Z*`
{tab} other implementation-defined characters

`_base-n-prefix_`:
{tab} `_base-n_` `*b*`

`_base-n_`:
{tab} a `_decimal-constant_` whose value is between 2 and 36

`_floating-constant_`:
{tab} `_decimal-floating-constant_`
{tab} `_base-n-floating-constant_`

`_decimal-floating-constant_`
{tab} `_fractional-constant_` `_exponent-part_`~opt~
{tab} `_digit-sequence_` `_exponent-part_`

`_base-n-floating-constant_`:
{tab} `_base-n-fractional-constant_` `_exponent-part_`~opt~
{tab} `_base-n-digit-sequence_` `_exponent-part_`~opt~

`_fractional-constant_`:
{tab} `_digit-sequence_`~opt~ `*.*` `_digit-sequence_`
{tab} `_digit-sequence_` `*.*`

`_exponent-part_`:
{tab} `*e*` `_sign_`~opt~ `_decimal-constant_`
{tab} `*e*` `_sign_`~opt~ `_base-n-constant_`

`_sign_`: one of
{tab} `*+*` `*-*`

`_base-n-fractional-constant_`:
{tab} `_base-n-digit-sequence_`~opt~ `*.*` `_base-n-digit-sequence_`
{tab} `_base-n-digit-sequence_` `*.*`

`_enuemration-constant_`:
{tab} `_identifier_`

`_character-constant_`:
{tab} `*'*` `_c-char-sequence_` `*'*`
{tab} `*{tick}*` `_w-char-sequence_` `*{tick}*`

`_c-char-sequence_`:
{tab} `_c-char_`
{tab} `_c-char-sequence_` `_c-char_`

`_c-char_`:
{tab} `_escape-sequence_`
{tab} any member of the source character set except `*'*`, `*\*`, or new-line character.

`_w-char-sequence_`:
{tab} `_w-char_`
{tab} `_w-char-sequence_` `_w-char_`

`_w-char_`:
{tab} `_escape-sequence_`
{tab} any member of the source chararcter set except `*{tick}*`, `*\*`, or new-line character.

`_escape-sequence_`:
{tab} `_simple-escape-sequence_`
{tab} `_octal-escape-sequence_`
{tab} `_hexadecimal-escape-sequence_`
{tab} `_universal-character-name_`

`_simple-escape-sequence_`: one of
{tab} `*\a*` `*\b*` `*\f*` `*\n*` `*\r*` `*\t*` `*\v*`
{tab} `*\'*` `*{stick}*` `*\"*` `*\\*` `*\?*`

`_octal-escape-sequence_`:
{tab} `*\*` `_octal-digit_`
{tab} `*\*` `_octal-digit_` `_octal-digit_`
{tab} `*\*` `_octal-digit_` `_octal-digit_` `_octal-digit_`

`_hexadecimal-escape-sequence_`:
{tab} `*\x*` `_hexadecimal-digit_`
{tab} `_hexadecimal-escape-sequence_` `_hexadecimal-digit_`

== String Literals
`_string-literal_`:
{tab} `_string-prefix_` `*"*` `_s-char-sequence_` `*"*`

`_string-prefix_`: one of
{tab} `*b*` `*B*` `*f*` `*F*` `*r*` `*R*`

`_s-char-sequence_`:
{tab} `_s-char_`
{tab} `_s-char-sequence_` `_s-char_`

`_s-char_`:
{tab} `_escape-sequence_`
{tab} any member of the source character set except `*"*`, `*\*`, or new-line charcter

== Operators
_All non-keyword operators are punctuators_

`_operator_`: one of
{tab} `*.*` `*\->*` `*++*` `*--*` `*%*` `*!*`
{tab} `*^*` `*@*` `*-*` `*~*` `*~<*` `*~>*` `*{star}*`
{tab} `*{star}{star}*` `*/*` `*+*`
{tab} `*<<*` `*>>*` `*&*` `*|*` `*$*`
{tab} `*<*` `*>*` `*\<=*` `*>=*` `*==*` `*!=*` `*\<\=>*`
{tab} `*=*` `*{star}{star}=*` `*{star}=*` `*/=*` `*%=*` `*+=*` `*-=*`
{tab} `*<\<=*` `*>>=*` `*&=*` `*|=*` `*$=*`

== Keyword Operators
_Keyword operators are both keywords and operators_

`_keyword-operator_`: one of
{tab} `*mod*`
{tab} `*and*` `*not*` `*or*`
{tab} `*in*` `*is*`

== Punctuators
`_punctuator_`: one of
{tab} `*[*` `*]*` `*(*` `*)*` `*{*` `*}*`
{tab} `*,*` `*:*`
{tab} `_indent_` `_line-end_`

`_indent_`:
{tab} four spaces
{tab} (through configuration) at least one space

`_EOF_`:
{tab} end of file character

`_line-end_`:
{tab} `*\n*`
{tab} `_EOF_`
