== Tokens

++++
<link rel="stylesheet" href="style.css" type="text/css">
++++

:tab: &nbsp;&nbsp;&nbsp;&nbsp;
:hardbreaks-option:

:lbracket: [
:star: *
:under: _

`_token_`:
{tab} `_keyword_`
{tab} `_identifier_`
{tab} `_constant_`
{tab} `_string-literal_`
{tab} `_operator_`
{tab} `_keyword-operator_`
{tab} `_punctuator_`

`_preprocessing-token_`:
{tab} `_header-name_`
{tab} `_identifier_`
{tab} `_preprocessing-number_`
{tab} `_character-constant_`
{tab} `_string-literal_`
{tab} `_operator_`
{tab} `_punctuator_`
{tab} each non-whitespace character that can't be one of the above

== Keywords
`_keyword_`: one of
{tab} `*align*` `*default*` `*else*` `*generic*`
{tab} `*if*` `*of*` `*size*`

== Identifiers
`_identifier_`:
{tab} `_identifier-nondigit_`
{tab} `_identifier_` `_identifier-nondigit_`
{tab} `_identifier_` `_digit_`

`_identifier-nondigit_`:
{tab} `_nondigit_`
{tab} `_universal-character-name_`
{tab} other implementation-defined characters

`_nondigit_`: one of
{tab} `*{under}*`
{tab} `_letter_`

`_letter_`: one of
{tab} english letters `*a*` to `*z*`
{tab} english letters `*A*` to `*Z*`

`_digit_`: one of
{tab} integers `*0*` to `*9*`

`_universal-character-name_`:
{tab} `*\u*` `_hex-quad_`
{tab} `*\U*` `_hex-quad_` `_hex-quad_`

`_hex-quad_`:
{tab} `_hexadecimal-digit_` `_hexadecimal-digit_` `_hexadecimal-digit_` `_hexadecimal-digit_`

== Constants
`_constant_`:
{tab} `_integer-constant_`
{tab} `_floating-constant_`
{tab} `_enumeration-constant_`
{tab} `_character-constant_`

`_integer-constant_`:
{tab} `_decimal-constant_` `_integer-suffix_`~opt~
{tab} `_base-n-constant_` `_integer-suffix_`~opt~

`_decimal-constant_`:
{tab} `_digit-sequence_`

`_digit-sequence_`:
{tab} `_digit_`
{tab} `_digit-sequence_` `_digit_`

`_base-n-constant_`:
{tab} `_base-n-digit-sequence_`

`_base-n-digit-sequence_`:
{tab} `_base-n-digit_` `_base-n-suffix_`
{tab} `_base-n-digit_` `_base-n-constant_`

`_base-n-digit_`: one of
{tab} `_letter_`
{tab} `_digit_`

`_base-n-suffix_`:
{tab} `*b*` `_base-n_`
{tab} `*B*` `_base-n_`

`_base-n_`:
{tab} a `_decimal-constant_` whose value is between 2 and 36

`_integer-suffix_`:
{tab} `_unsigned-suffix_` `_long-suffix_`~opt~
{tab} `_unsigned-suffix_` `_long-long-suffix_`~opt~
{tab} `_long-suffix_` `_unsigned-suffix_`~opt~
{tab} `_long-long-suffix_` `_unsigned-suffix_`~opt~

`_unsigned-suffix_`:
{tab} `*u*` `*U*`

`_long-suffix_`:
{tab} `*l*` `*L*`

`_long-long-suffix_`:
{tab} `*ll*` `*LL*`

`_floating-constant_`:
{tab} `_decimal-floating-constant_`
{tab} `_base-n-floating-constant_`

`_decimal-floating-constant_`
{tab} `_fractional-constant_` `_exponent-part_`~opt~ `_floating-suffix_`~opt~
{tab} `_digit-sequence_` `_exponent-part_` `_floating-suffix_`~opt~

`_base-n-floating-constant_`:
{tab} `_base-n-fractional-constant_` `_base-n-exponent-part_`~opt~ `_floating-suffix_`~opt~
{tab} `_base-n-digit-sequence_` `_base-n-exponent-part_` `_floating-suffix_`~opt~

`_fractional-constant_`:
{tab} `_digit-sequence_`~opt~ `*.*` `_digit-sequence_`
{tab} `_digit-sequence_` `*.*`

`_exponent-part_`:
{tab} `*e*` `_sign_`~opt~ `_decimal-constant_`
{tab} `*E*` `_sign_`~opt~ `_decimal-constant_`

`_sign_`: one of
{tab} `*+*` `*-*`

`_base-n-fractional-constant_`:
{tab} `_base-n-digit-sequence_`~opt~ `*.*` `_base-n-digit-sequence_`
{tab} `_base-n-digit-sequence_` `*.*`

`_base-n-exponent-part_`:
{tab} `*e*` `_sign_`~opt~ `_base-n-constant_`
{tab} `*E*` `_sign_`~opt~ `_base-n-constant_`

`_floating-suffix_`: one of
{tab} `*f*` `*F*` `*l*` `*L*`

`_enuemration-constant_`:
{tab} `_identifier_`

`_character-constant_`:
{tab} `*'*` `_c-char-sequence_` `*'*`
{tab} `*L'*` `_c-char-sequence_` `*'*`

`_c-char-sequence_`:
{tab} `_c-char_`
{tab} `_c-char-sequence_` `_c-char_`

`_c-char_`:
{tab} `_escape-sequence_`
{tab} any member of the source character set except `*'*`, `*\*`, or new-line character.

`_escape-sequence_`:
{tab} `_simple-escape-sequence_`
{tab} `_octal-escape-sequence_`
{tab} `_hexadecimal-escape-sequence_`
{tab} `_universal-character-name_`

`_simple-escape-sequence_`: one of
{tab} `*\a*` `*\b*` `*\f*` `*\n*` `*\r*` `*\t*` `*\v*`
{tab} `*\'*` `*\"*` `*\\*` `*\?*`

`_octal-escape-sequence_`:
{tab} `*\*` `_octal-digit_`
{tab} `*\*` `_octal-digit_` `_octal-digit_`
{tab} `*\*` `_octal-digit_` `_octal-digit_` `_octal-digit_`

`_hexadecimal-escape-sequence_`:
{tab} `*\x*` `_hexadecimal-digit_`
{tab} `_hexadecimal-escape-sequence_` `_hexadecimal-digit_`

== String Literals
`_string-literal_`:
{tab} `_string-prefix_` `*"*` `_s-char-sequence_` `*"*`

`_string-prefix_`: one of
{tab} `*b*` `*f*` `*r*`
{tab} `_size-prefix_`

`_size-prefix_`:
{tab} `_decimal-constant_`
{tab} `_base-n-constant_`

`_s-char_`
{tab} `_escape-sequence_`
{tab} any member of the source character set except `*"*`, `*\*`, or new-line charcter

== Operators
_All non-keyword operators are punctuators_

`_operator_`: one of
{tab} `*.*` `*\->*` `*++*` `*--*` `*%*` `*!*`
{tab} `*^*` `*@*` `*+*` `*-*` `*~*` `*~<*` `*~>*`
{tab} `*{star}{star}*` `*{star}*` `*/*`
{tab} `*<<*` `*>>*` `*&*` `*|*` `*$*`
{tab} `*<*` `*>*` `*\<=*` `*>=*` `*==*` `*!=*`
{tab} `*=*` `*{star}{star}=*` `*{star}=*` `*/=*` `*%=*` `*+=*` `*-=*`
{tab} `*<\<=*` `*>>=*` `*&=*` `*|=*` `*$=*`

== Keyword Operators
_Keyword operators are both keywords and operators_

`_keyword-operator_`: one of
{tab} `*and*` `*mod*` `*not*` `*or*`

== Punctuators
`_punctuator_`: one of
{tab} `*{lbracket}*` `*]*` `*(*` `*)*` `*|*`
{tab} `*,*`
{tab} `_indent_` `*\n*`

`_indent_`:
{tab} four spaces
{tab} (through the configurator) at least one space

== Header Names
`_header-name_`:
{tab} `*<*` `_h-char-sequence_` `*>*`
{tab} `*"*` `_q-char-sequence_` `*"*`

`_h-char-sequence_`:
{tab} `_h-char_`
{tab} `_h-char-sequence_` `_h-char_`

`_h-char_`:
{tab} any member of the source character set except the new-line character and `*>*`

`_q-char-sequence_`:
{tab} `_q-char_`
{tab} `_q-char-sequence_` `_q-char_`

`_q-char_`:
{tab} any member of the source character set except the new-line character and `*"*`

== Preprocessing Numbers
`_preprocessing-number_`:
{tab} `_digit_`
{tab} `*.*` `_digit_`
{tab} `_preprocessing-number_` `_digit_`
{tab} `_preprocessing-number_` `identifier-nondigit`
{tab} `_preprocessing-number_` `*e*` `_sign_`
{tab} `_preprocessing-number_` `*E*` `_sign_`
{tab} `_preprocessing-number_` `*p*` `_sign_`
{tab} `_preprocessing-number_` `*P*` `_sign_`
{tab} `_preprocessing-number_` `*.*`
